
services:
  honeybadger_swarm:
    build: ./dashboards/swarm
    container_name: honeybadger_swarm
    expose:
      - "8181"
    restart: always

  nginx_proxy:
    image: nginx:1.27-alpine
    container_name: honeybadger_nginx
    depends_on:
      - honeybadger_swarm
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    restart: always

  certbot:
    image: certbot/certbot
    container_name: honeybadger_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM;
             while :;
             do certbot renew --quiet;
             sleep 12h;
             done"
